version: '3.1'

services:
    cf_flowise:
        build:
          context: ./
          dockerfile: Dockerfile
        image: llm-in-a-box
        container_name: cf_flowise_214
        restart: always
        env_file:
             - .env
        ports:
          - 3000:3000
