version: '3.1'

services:
    cf_flowise:
        build:
          context: ./
          dockerfile: Dockerfile
        image: cf-llm-box
        container_name: cf_flowise
        restart: always
        env_file:
             - .env
        ports:
          - 3000:3000
